safe: true
markdown: kramdown
pygments: true
permalink: /:title.html

default_theme: yandex
default_width: 792
default_lang: ru
default_body_class: list

author:
    name: Yours Truly
    # url:  http://example.com/
    company:
        name: Яндекс
        url:  http://yandex.ru/

progress: true
