safe: true
markdown: kramdown
highlighter: pygments
permalink: /:title.html
exclude: [ assets ]

default_theme: yandex
default_width: 792
default_lang: ru
default_body_class: list

author:
    name: Автор
    position: Должность
    company:
        name: Яндекс
        url:  http://yandex.ru/

progress: true
